# -*- coding: utf-8 -*-
"""
Main entry point and execution harness for Track A Trading Strategy Pipeline.

This script chains the three elements:
1. YouTubeIngestionService: Extracts video ID, fetches transcripts (manual or auto-fallback).
2. StrategyExtractionService: Submits transcript text to Gemini for structured JSON retrieval.
3. StorageService: Stores resulting StrategyObjects flatly in an SQLite database.

Usage:
    python main.py --url "<youtube_url>"
    
If no URL is provided, the harness offers a clean, interactive command-line interface.
"""

import sys
import argparse
from ingestion import YouTubeIngestionService, IngestionError
from extractor import StrategyExtractionService
from storage import StorageService, StateMachineError


def run_pipeline(url: str, custom_db_path: str = "strategies.db") -> None:
    """
    Executes the entire end-to-end Track A strategy extraction pipeline.
    
    Args:
        url: Full YouTube URL or a direct 11-char video ID.
        custom_db_path: SQLite DB path to use for saving results.
    """
    print("\n" + "="*60)
    print("STARTING TRACK A TRADING STRATEGY EXTRACTION PIPELINE")
    print("="*60)
    print(f"Step 1: Parsing and ingesting video transcript from:\n   --> {url}")
    
    # 1. Ingest YouTube Video Transcript
    ingestion_service = YouTubeIngestionService()
    try:
        transcript_data = ingestion_service.fetch_transcript(url)
        print(f"✔ Transcript successfully retrieved! ({len(transcript_data.transcript)} chars)")
        print(f"  Video ID: {transcript_data.video_id}")
        print(f"  Language detected: '{transcript_data.transcript_language}'")
    except IngestionError as ing_err:
        print(f"❌ Ingestion Error: {str(ing_err)}")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Unexpected Ingestion Exception: {str(e)}")
        sys.exit(1)

    print("\nStep 2: Sending transcript to Gemini client for strategy extraction")
    print("        (Structured JSON validation with Pydantic schemas)")
    
    # 2. Call Gemini extraction API
    extractor = StrategyExtractionService()
    try:
        # Note: In a production environment, video metadata like Title and Channel 
        # is typically pulled from YouTube API. Here we supply descriptors.
        strategy_obj = extractor.extract_strategy(
            transcript_text=transcript_data.transcript,
            video_url=transcript_data.url,
            video_title="Extracted YouTube Strategy Video",
            channel_name="Quantitative Trading Source"
        )
        print("✔ Strategy structured data successfully generated by Gemini!")
        print(f"  Strategy Name: '{strategy_obj.name}'")
        print(f"  Asset Class:   {strategy_obj.asset_class}")
        print(f"  Timeframe:     {strategy_obj.timeframe}")
        print(f"  Indicators:    {', '.join(strategy_obj.indicators) if strategy_obj.indicators else 'None'}")
        print(f"  Confidence:    {strategy_obj.extraction_confidence:.2f} / 1.00")
        
        if strategy_obj.extraction_notes:
            print(f"  Extraction Notes: {strategy_obj.extraction_notes}")
            
    except RuntimeError as api_err:
        print(f"❌ Extraction Error: {str(api_err)}")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Unexpected Extraction Exception: {str(e)}")
        sys.exit(1)

    print("\nStep 3: Storing Strategy record in SQLite Database")
    
    # 3. Store the StrategyObject in SQLite
    storage = StorageService(db_path=custom_db_path)
    try:
        storage.insert_strategy(strategy_obj)
        print(f"✔ Strategy successfully persisted to {custom_db_path}!")
        print(f"  Record UUID: {strategy_obj.id}")
        print(f"  Pipeline Status: '{strategy_obj.status}'")
    except Exception as db_err:
        print(f"❌ Database Insertion Error: {str(db_err)}")
        sys.exit(1)

    # 4. Demonstrate State Machine transition validation and updates
    print("\nStep 4: Database query validation and state transition test")
    try:
        # Fetch back from database to verify integrity
        queried = storage.get_strategy(strategy_obj.id)
        if queried:
            print("✔ Database record retrieved successfully and integrity verified.")
            
            # Show update of backtest metrics independently of pipeline progression
            print("  Demonstrating backtest metric update...")
            test_backtest_metrics = {
                "sharpe_ratio": 1.84,
                "max_drawdown_percent": 11.2,
                "win_rate": 0.58,
                "profit_factor": 1.45,
                "total_trades": 124
            }
            storage.update_backtest_metrics(queried.id, test_backtest_metrics)
            print("  ✔ Backtest metrics successfully attached in DB.")

            # Show valid transition check
            print("  Progressing pipeline status: 'extracted' -> 'backtested'")
            storage.update_status(queried.id, "backtested")
            
            # Fetch again to show state change
            updated_obj = storage.get_strategy(queried.id)
            print(f"  ✔ Status updated successfully! New status in DB: '{updated_obj.status}'")
            print(f"    Stored Backtest Metrics: {updated_obj.backtest_metrics}")
            
            # Show invalid transition denial check
            print("  Attempting ILLEGAL transition: 'backtested' -> 'live' (should bypass paper_trading)")
            try:
                storage.update_status(queried.id, "live")
                print("  ❌ WARNING: Invalid state transition bypassed checks!")
            except StateMachineError as state_err:
                print(f"  ✔ SUCCESS: Illegal transition successfully intercepted and blocked!")
                print(f"    Error triggered as expected: {str(state_err)}")
                
    except Exception as pipe_err:
        print(f"❌ Database Validation Testing Failed: {str(pipe_err)}")
        sys.exit(1)
        
    print("\n" + "="*60)
    print("PIPELINE TEST COMPLETED SUCCESSFULLY!")
    print("="*60 + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Track A Strategy Extraction Pipeline Harness")
    parser.add_argument(
        "--url", 
        type=str, 
        help="YouTube Video URL (watch?v=, youtu.be, shorts/, embed/) or direct 11-char Video ID."
    )
    args = parser.parse_args()
    
    if args.url:
        run_pipeline(args.url)
    else:
        print("\n=== Track A: Trading Strategy Extraction Pipeline Runner ===")
        print("Provide a YouTube URL to test the interactive pipeline.")
        print("Example: python main.py --url \"https://www.youtube.com/watch?v=dQw4w9WgXcQ\"")
        print("-" * 60)
        
        user_input = input("Enter YouTube URL (or press Enter to run mock with direct ID 'dQw4w9WgXcQ'): ").strip()
        if not user_input:
            user_input = "dQw4w9WgXcQ"
            
        run_pipeline(user_input)
